config/routes.rb
Twark::Application.routes.draw do
  get "testpage/show"
  resources :web_apps
  resources :events, except: [:edit, :update]

  match 'events' => "events#index", via: :options
  

  root 'welcome#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :web_app

end

app/models/web_app.rb
class WebApp < ActiveRecord::Base
  has_many :events, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_headers
  skip_before_action :verfiy_authenticity_token

  def index
  end

  def create
    @webapp = WebApp.where(token: params[:token]).first
    @event = @webapp.events.build(params.require(:event).permit(:name, :value))
    @event.value = request.remote_ip
    @event.save
  end

  def destroy
  end

  def show
  end


  private

  def set_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
    headers['Access-Control-Max-Age'] = '1728000'    
  end

end

app/controllers/testpage_controller.rb
class TestpageController < ApplicationController
  def show
  end
end

app/controllers/web_apps_controller.rb
class WebAppsController < ApplicationController
  before_action :set_web_app, only: [:show, :edit, :update, :destroy]

  # GET /web_apps
  # GET /web_apps.json
  def index
    @web_apps = WebApp.all
  end


  # GET /web_apps/1
  # GET /web_apps/1.json
  def show
    @events = @web_app.events
    # Find unique event names
    @event_types = @events.pluck(:name).uniq
  end

  # GET /web_apps/new
  def new
    @web_app = WebApp.new
  end

  # GET /web_apps/1/edit
  def edit
  end

  # POST /web_apps
  # POST /web_apps.json
  def create
    @web_app = WebApp.new(web_app_params)
    @token = SecureRandom.hex(8)
    @web_app.update_attribute(:token, @token)

    respond_to do |format|
      if @web_app.save
        format.html { redirect_to @web_app, notice: 'Web app was successfully created.' }
        format.json { render action: 'show', status: :created, location: @web_app }
      else
        format.html { render action: 'new' }
        format.json { render json: @web_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /web_apps/1
  # PATCH/PUT /web_apps/1.json
  def update
    respond_to do |format|
      if @web_app.update(web_app_params)
        format.html { redirect_to @web_app, notice: 'Web app was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @web_app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /web_apps/1
  # DELETE /web_apps/1.json
  def destroy
    @web_app.destroy
    respond_to do |format|
      format.html { redirect_to web_apps_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_web_app
      @web_app = WebApp.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def web_app_params
      params.require(:web_app).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/testpage_helper.rb
module TestpageHelper
end

app/helpers/web_apps_helper.rb
module WebAppsHelper

  def group_events_by_date(events, type)
    events.where(name: type).order(:created_at).group(:created_at).count
  end

  def ChartData(events, type)

    data = {}

    # Convert :created_at values to dates and propogate @data hash
    group_events_by_date(events, type).each do |key, value|
      
      if data.has_key?(key.to_date)
        data[key.to_date] += value
      else
        data[key.to_date] = value
      end
    end

    # Use first and last ordered keys from data hash to generate date range
    # Use to limit chart timeline:
      # date_range = ((data.keys.last - 1.month) .. data.keys.last).to_a 
    date_range = (data.keys.first .. data.keys.last).to_a

    # Check for events by date and fill value range with event count data
    value_range = []

    date_range.each do |date|
      if data.has_key?(date)
        value_range << data[date]
      else
        value_range << 0
      end
    end

    # Convert date range to chart friendly format
    date_range.map! do |date|
      date.strftime("%m-%d-%Y")
    end

    label_val_array = [date_range, value_range]   
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twark</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/testpage/show.html.erb
<h1>Testpage#show</h1>
<p>Find me in app/views/testpage/show.html.erb</p>
<%= link_to "Test Click!!!", testpage_show_path, class: "tracked" %>

app/views/web_apps/_form.html.erb
<%= form_for(@web_app) do |f| %>
  <% if @web_app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_app.errors.count, "error") %> prohibited this web_app from being saved:</h2>

      <ul>
      <% @web_app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/web_apps/edit.html.erb
<h1>Editing web_app</h1>

<%= render 'form' %>

<%= link_to 'Show', @web_app %> |
<%= link_to 'Back', web_apps_path %>

app/views/web_apps/index.html.erb
<h1>Listing web_apps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Token</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @web_apps.each do |web_app| %>
      <tr>
        <td><%= web_app.name %></td>
        <td><%= web_app.token %></td>
        <td><%= link_to 'Show', web_app %></td>
        <td><%= link_to 'Edit', edit_web_app_path(web_app) %></td>
        <td><%= link_to 'Destroy', web_app, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Web app', new_web_app_path %>

app/views/web_apps/new.html.erb
<h1>New web_app</h1>

<%= render 'form' %>

<%= link_to 'Back', web_apps_path %>

app/views/web_apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @web_app.name %>
  <strong>Token:</strong>
  <%= @web_app.token %>
</p>

<%= link_to 'Edit', edit_web_app_path(@web_app) %> |
<%= link_to 'Back', web_apps_path %>

<% @event_types.each do |type| %>

  <% chartdata = ChartData(@events, type) %>
  <p><h3><%= type %></h3></p>

  <p><canvas id= <%= type %> width="600", height="400"></canvas></p>

  <script>
    $(document).ready(function(){
      GenerateChart("<%= type %>", <%= raw chartdata.first %>, <%= chartdata.last %>);
    })
  </script>

  <p><%= raw chartdata.first %></p>
  <p><%= raw chartdata.last %></p>

  <br />
<% end %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

<%= link_to 'WebApps', web_apps_path %>
<%= link_to 'Test Event Page', testpage_show_path %>